name: Easeatten Android Tagged Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            app/src/main/rust/sxcapi/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('app/src/main/rust/sxcapi/Cargo.lock') }}

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: jetbrains

      # Configure Gradle for optimal use in GitHub Actions, including caching
      # of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup cargo-binstall for Rust dependencies
        uses: cargo-bins/cargo-binstall@main

      - name: Setup Rust binary dependencies
        run: |
          cargo binstall cargo-ndk # Quick install skipping compilation.
          cargo install uniffi --features cli --bin uniffi-bindgen

      - name: Setup Rust toolchain
        run: rustup target add armv7-linux-androideabi aarch64-linux-android x86_64-linux-android

      - name: Assemble with Gradle
        run: ./gradlew assemble

      - name: Sign APKs
        uses: ilharp/sign-android-release@v2
        id: apksigner
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.APKSIGNER_SIGNING_KEY }}
          keyAlias: ${{ secrets.APKSIGNER_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.APKSIGNER_KEY_STORE_PASSWORD }}

      - name: Get APK files
        uses: jungwinter/split@v2
        id: apksigner_files
        with:
          msg: ${{ steps.apksigner.outputs.signedFiles }}
          separator: ':'

      - name: Create Release on GitHub
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          files: | # APK files for ABIs: armeabi-v7a, arm64-v8a, x86_64
            ${{ steps.apksigner_files.outputs._0 }}
            ${{ steps.apksigner_files.outputs._1 }}
            ${{ steps.apksigner_files.outputs._2 }}
